### ISSUE TITLE
Integrating AWS Cognito

### ISSUE THREAD

**Issue by Nashluffy** [Nashluffy/SkyAudio#34]
Check out [this link](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) for more info. 

While we could setup our own database for users, AWS Cognito is a part of free tier and offers a lot of integrated services. 

This involves adding in the new registration page on the front end, and changing some flask to route-up registration page.

**Comment by Nashluffy** [comment]
@pressure101 

https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html

**Comment by pressure101** [comment]
![cognito_error](https://user-images.githubusercontent.com/18617240/65890041-4382d200-e370-11e9-9a83-4c59b0203d25.png)
