### ISSUE TITLE
Access rabbitMQ through port and not local host

### ISSUE THREAD

**Issue by Nashluffy** [Nashluffy/SkyAudio#39]
When running the flask development server, we cannot communicate with our RabbitMQ container. We can produce Nameko RPC calls, but not push them to RabbitMQ. 

This involves changing the CONFIG in the SkyAudio.py flask file.

**Comment by Nashluffy** [comment]
https://www.rabbitmq.com/access-control.html

**Comment by Nashluffy** [comment]
@leedagr8 Got this working. You can now make calls to our backend from development environment. 

Still need to setup proper security credentials for this. For the time being, we admit/deny based on AWS security groups for the EC2 instance. I need to setup RabbitMQ credentials for everyone.

**Comment by leedagr8** [comment]
Sounds good man. Nice work @Nashluffy
