### ISSUE TITLE
pysndfx broken - effects library not compiling

### ISSUE THREAD

**Issue by twantheswan** [Nashluffy/SkyAudio#42]
Current library pysndfx stopped working. Could be an issue with the python version, bad code, or maybe it just became an unusable library. Going to try to find a fix since the library was well laid out for our use case. If I can't I will have to find another DSP library and remake functions.

rip

**Comment by Nashluffy** [comment]
We worked on this for about an hour today. Looked at the following

- Support for pysndfx -- looks like it might be unsupported as last update was almost a year ago
- Could submit an issue and hope for a respose
- Is it worth trying to fix, or should we focus on finding a new library
- Don't think it's an issue of Python not importing the module, think it's an issue with the library itself

**Comment by Nashluffy** [comment]
@twantheswan I'm still getting errors with mine. It compiles fine ("python3 reverb.py" or "python2.7 reverb.py", but when I call the function SmallRoom, I still get errors. How did you test? What are you passing in as the waveform? We still have inf declared but never use it. Can you confirm that the waveform was modified and output?

I tested with Python3.6 and Python2.7, no luck. I removed the waveform argument from SmallRoom and still no luck. I called SmallRoom from python CLI and within the file itself, neither worked. 

![Screenshot from 2019-09-22 18-46-36](https://user-images.githubusercontent.com/11613073/65395542-3a8b7280-dd6a-11e9-8629-28ce79f1b0b9.png)
![Screenshot from 2019-09-22 18-49-55](https://user-images.githubusercontent.com/11613073/65395543-3c553600-dd6a-11e9-95ed-cd89a9a98198.png)

**Comment by twantheswan** [comment]
You need to pass waveform for it to work. All you should need to call it is: SmallRoom()

Try to run it with a .wav file inside the same directory as reverb.py and  assign inf = 'nameOfFile.wav' & outf = 'outputName.wav'

Can you send a screenshot of the import pysndfx line as well?

**Comment by Nashluffy** [comment]
@twantheswan My import statement is what you pushed up to the branch. Don't worry about trying to make it work on production, just push what works locally and I'll make it work on production. 

Otherwise, I don't know what to change and what not to change.

**Comment by twantheswan** [comment]
@Nashluffy  I added the full fix that worked for me locally. Its not the cleanest since the library is directly in the backend folder, but we can move it around once we know it works on your end.

**Comment by Nashluffy** [comment]
@twantheswan Thanks, I'll take a look at it tonight or tomorrow.

**Comment by Nashluffy** [comment]
@twantheswan This is fixed in the most recent commit of this branch. Gonna make a PR and close this.
