### ISSUE TITLE
File type being sent in form data is not a wav

### ISSUE THREAD

**Issue by Nashluffy** [Nashluffy/SkyAudio#55]
@leedagr8 @twantheswan Just got done testing our audio engine, confirms it works with .wav files. 

Went to do a full test, which includes downloading the audio recording from the website. Whatever we are getting is not a .wav, and causes errors with our audio engine. I'd like to look into this together.

**Comment by leedagr8** [comment]
Hey @Nashluffy lets look at it whenever you have time. What is the return type?

**Comment by Nashluffy** [comment]
@leedagr8 Here's a screenshot of what I'm getting. It looks like it's a html/text file. Not sure how this happened.

![Screenshot from 2019-10-03 08-57-57](https://user-images.githubusercontent.com/11613073/66128531-001ca380-e5bc-11e9-887d-f2acf053df8e.png)

**Comment by Nashluffy** [comment]
@leedagr8 https://medium.com/@bryanjenningz/how-to-record-and-play-audio-in-javascript-faa1b2b3e49b

**Comment by Nashluffy** [comment]
@leedagr8 @twantheswan Hey so I did some testing on this issue. Seems like we're not fully converting the blob to a wav file, maybe we're missing some header data or something. Below is what I tried.

1. Spin up dev server of SkyAudio, record some music and play it back on my computer. My default media player was able to play it, so I know it was a .wav file. 

2. I sent it over to the server and tried to process it, same issue came up as we were having before. This was expected.

3. I then tried sending the wav file through an online converter (wav to wav), then repeating step two. Magically, the audio engine was able to process the file now.

4. In conclusion, I think we're missing some sort of metadata that the audio engine requires. I'm not sure what it is, but we can mess around with it more at a later date.

As kind of a hot-fix to please our overlords, I'm going to see how difficult it would be to implement an audio-conversion on the server, even though this is really inefficient, it would work (we just proved it)

**Comment by Nashluffy** [comment]
Turns out it was an OGG file being sent over. Not really sure why when it was specified to be a WAV, but we just switched to OGG.
