### ISSUE TITLE
homeEdit Branch

### ISSUE THREAD

**Issue by leedagr8** [Nashluffy/SkyAudio#63]
@Nashluffy @twantheswan @pressure101  I changed the waveform color also.. i added a cursor. Check out the screenshot below to see what I mean

![image](https://user-images.githubusercontent.com/26153230/66601123-22429280-eb75-11e9-8492-052f0f9a94b4.png)

If you look to the right of the number you can see a black veritcal line. When you select a region it adds a vertical line there. Also the cursor shows the time of the track. Looking into adding a region soon

**Comment by Nashluffy** [comment]
@leedagr8 That looks awesome man. I'm just wondering what we'll do about the navigation bar. Did you make this branch from master, like is it a new branch? Or is it a continuation of the navigation bar branch

**Comment by leedagr8** [comment]
![image](https://user-images.githubusercontent.com/26153230/66623186-8c305b80-ebb8-11e9-9ef1-7714f610e955.png)

New look @Nashluffy @twantheswan @pressure101
